### ISSUE TITLE
add event information in each execution

### ISSUE THREAD

**Issue by j0nl1** [nymlab/vectis#116]
Currently now we are adding attributes in the wasm execution which sometimes make more difficult to find those events.

```rs
Ok(Response::new()
        .add_message(msg)
        .add_attribute("action", "execute_ibc_transfer")
        .add_attribute("to", rcv.addr)
        .add_attribute("channel_id", channel_id)
        .add_attribute("amount", Coin { denom, amount }.to_string()))
```

Will be nice to have our own events as the next example using the next convention:
vectis.{contract_name}.{version}.Msg{execute_msg_name}

```rs
    let event = Event::new("vectis.dao_tunnel.v1.MsgIbcTransfer")
        .add_attribute("to", rcv.addr)
        .add_attribute("channel_id", channel_id)
        .add_attribute("amount", Coin { denom, amount }.to_string()));

    Ok(Response::new()
        .add_event(event))
```

This will make much easier to find tx using those events and indexer approach for this will be:

```yaml
- handler: onIbcTransfer
          kind: cosmos/EventHandler
          filter:
            type: "wasm-vectis.dao_tunnel.v1.MsgIbcTransfer"
          messageFilter:
              values:
                _contract_address: {contract_name}
```
